### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by YannikSc** [rpi-ws281x/rpi-ws281x-rust#15]
Hey, I'm having a short question regarding the maintenance of the project .. there are a couple open pull requests and the project overall seem not to be active that much anymore. Is someone working on it? If not I would *carefully* volunteer to keep an eye on it because I'm currently working on a small IoT system, which implements some LED related functions with the help of this library and there are some things (espacially in the pull requests) that I would like to have.

**Comment by JMurph2015** [comment]
Hi! Sorry this has been so quiet recently.  This is mostly maintained if/when I actually check my personal email and have time to sort through the GitHub stuff.  I tried to cover the basics so that it's feature complete for my purposes but I could totally see that people would want to expand on.  If you're interested, I can make you a contributor as well to try to look after the incidental PR.

Some notes for direction of the project:
    * The goal is to represent the features of the underlying driver in a reasonably idiomatic Rust format, nothing more nothing less.
    * Ideally we want to be able to track upstream rpi-ws281x without too many changes release-to-release which is why there is heavy use of bindgen.  There has been one other attempt to wrap rpi-ws281x in Rust, but all of the FFI was manual and it made it prohibitively difficult to update to newer versions of the driver.

**Comment by YannikSc** [comment]
Hey, thanks for the invite. Although I'm fairly new to Rust, I got your point here. 
My plan is not to add functionallity but more like adding support for accessing the fields of the underlaying library. 
So I think we're going roughly in the same direction.
